# Project: MergeSort
# Makefile created by Dev-C++ 5.9.0

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main(m).o MergeSort.o
LINKOBJ  = main(m).o MergeSort.o
LIBS     = -L"E:/Dev-c++/Dev-Cpp/MinGW64/lib" -L"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg -g3
INCS     = -I"E:/Dev-c++/Dev-Cpp/MinGW64/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/Dev-c++/Dev-Cpp/MinGW64/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = MergeSort.exe
CXXFLAGS = $(CXXINCS) -pg -g3
CFLAGS   = $(INCS) -pg -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main(m).o: main(m).cpp
	$(CPP) -c main(m).cpp -o main(m).o $(CXXFLAGS)

MergeSort.o: MergeSort.cpp
	$(CPP) -c MergeSort.cpp -o MergeSort.o $(CXXFLAGS)
